=== TrevisanFabio/EsercizioEsempioDTD/DTD Esercizi/agenda.dtd
<!ELEMENT agenda (contatto*)>
<!ELEMENT contatto (nome,indirizzo+,telefono*,email*,foto*)>
<!ELEMENT nome (#PCDATA)>
<!ELEMENT indirizzo (via, numero, citta, cap, provincia?)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT citta (#PCDATA)>
<!ELEMENT cap (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono tipo (casa | ufficio | cellulare) 'casa'>
<!ELEMENT email (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto src CDATA #REQUIRED desc CDATA #IMPLIED>
<!ENTITY BO "40100">
<!ENTITY MO "41100">
<!ENTITY RE "42100">

=== TrevisanFabio/EsercizioEsempioDTD/DTD Esercizi/Agenda.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE agenda SYSTEM "agenda.dtd">
<agenda>
    <contatto>
        <nome>PincoPallino</nome>
    <indirizzo>
        <via>Via Incognita</via>
        <numero>10</numero>
        <citta>Bologna</citta>
        <cap>&BO;</cap>
    </indirizzo>
    <telefono>050-123456</telefono>
    <telefono tipo="ufficio">051-123456</telefono>
    <email>pinco@email.com</email>
    <foto src="pinco.gif" desc="acunamatata"></foto>
    </contatto>
</agenda>
